services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=catalogo-do-sabio'
      - 'MONGO_INITDB_ROOT_PASSWORD=pass'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
    ports:
      - '27017'