services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=o-catalogo-do-sabio
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    expose:
      - 27017
    ports:
      - '27017:27017'
  redis-server:
    hostname: redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
  spring-application:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_started
      redis-server:
        condition: service_started

networks:
  default:
    name: localhost