spring:
  application:
    name: catalogo-do-sabio

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      port: 27017
      host: mongodb
      username: user
      password: pass
      database: catalogo-do-sabio